/**
 * The campus routing knowledge as a document: what the research holds, how UW Go uses each part of
 * it, what the sources disagree about, and what someone should walk out and check. Rendered by
 * scripts/audit-campus-routing.mjs into docs/campus-routing-audit.md; a test keeps that file current.
 *
 * Type-only imports: Node loads this file directly for the audit script.
 */
import type { CampusKnowledge, SurveyedEdge } from "./knowledge";
import type { Activation, Evidence, FieldCheck } from "./types";

const EVIDENCE: readonly Evidence[] = ["OFFICIAL", "FIELD_VERIFIED", "CORROBORATED", "SURVEYED", "ANECDOTAL", "INFERRED", "UNRESOLVED"];
const ACTIVATION: readonly Activation[] = ["ACTIVE", "EXPERIMENTAL", "QUARANTINED", "HISTORICAL"];

const lower = (s: string) => s.toLowerCase();
const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
const count = <T>(items: readonly T[], f: (t: T) => boolean) => items.filter(f).length;

function table(head: readonly string[], rows: readonly (readonly string[])[]): string[] {
  return [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`, ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`)];
}

export function renderCampusAudit(k: CampusKnowledge, surveyed: ReadonlyMap<string, SurveyedEdge>): string {
  const r = k.research;
  const o = k.overlay;
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines);

  push(
    "# Campus routing knowledge audit",
    "",
    `Generated by \`scripts/audit-campus-routing.mjs\` from the research package of ${r.asOf} (\`src/data/campus/research/\`) and UW Go's reviewed decisions in \`src/data/campus/overlay.ts\` (reviewed ${o.reviewedAt}). Do not edit by hand; a test fails when this file is out of date.`,
    "",
    "## What the research holds",
    "",
    ...table(["Buildings", "Door groups", "Connections", "Route candidates", "Rules", "Sources"], [[`${r.buildings.length}`, `${r.portals.length}`, `${r.connections.length}`, `${r.routeCandidates.length}`, `${r.rules.length}`, `${r.sources.length}`]]),
    "",
    `Status: \`${r.status}\`. Every record has routing disabled. No record has coordinates, opening hours or a measured time; the research lists these as unknown everywhere: ${r.globalUnknowns.join(", ")}.`,
    "",
    ...table(["Source type", "Count", "UW Go evidence"], ["official", "student_journalism", "community_anecdote", "historical_blog"].map((t) => {
      const of = r.sources.filter((s) => s.sourceType === t);
      return [t, `${of.length}`, of[0] ? lower(of[0].evidence) : "-"];
    })),
    "",
    ...table(["Door groups by evidence", "Count"], EVIDENCE.map((e) => [lower(e), `${count(r.portals, (p) => p.evidence === e)}`]).filter(([, n]) => n !== "0")),
    "",
  );

  push("## How routing uses it", "");
  push(
    "Research records never route on their own. A fact is attached to a surveyed segment by UW Go's overlay, and routing uses it as its activation says. Restrictions (a door that may not be used inwards, a link that is not step-free) apply whatever their evidence; anything that widens what a route may use needs official or corroborated evidence.",
    "",
    ...table(["Activation", ...EVIDENCE.map(lower)], ACTIVATION.map((a) => [lower(a), ...EVIDENCE.map((e) => `${count(o.edges, (f) => f.activation === a && f.evidence === e)}`)])),
    "",
  );
  const notActive = o.edges.filter((f) => f.activation !== "ACTIVE");
  if (notActive.length) {
    push("Segments the survey has that routing does not use:", "");
    for (const f of notActive) push(`- **${f.label}** (\`${f.ref.edgeId}\`, ${lower(f.activation)}): ${f.basis}`);
    push("");
  }

  push("## Buildings with a rule about their map point", "");
  for (const b of o.buildings.filter((x) => x.exterior)) {
    const e = b.exterior!;
    push(`- **${b.code}**: in ${lower(e.in)}, out ${lower(e.out)} (${e.portalIds.join(", ")}; ${lower(e.evidence)}; ${e.sourceIds.join(", ")}). ${e.basis}`, `  - Told to students: "${e.arrivalAdvice}"`);
  }
  push("");

  push("## Door groups matched to surveyed doors", "");
  const placements = o.edges.filter((f) => f.ref.kind === "DOOR" && f.ref.between.includes("OUT"));
  push(...table(["Surveyed door", "Research", "Evidence", "Why"], placements.map((f) => {
    const portals = (f.research?.portals ?? []).map((id) => `${id} "${k.portals.get(id)?.description ?? "?"}"`).join("; ");
    return [`${f.label} (\`${f.ref.edgeId}\`)`, portals || (f.research?.rules ?? []).join(", "), lower(f.evidence), f.basis];
  })));
  const placed = new Set(placements.flatMap((f) => f.research?.portals ?? []));
  const unplaced = r.portals.filter((p) => !placed.has(p.id));
  push("", `${unplaced.length} of ${r.portals.length} research door groups are not matched to any surveyed door, because the survey has no door on the side described or more than one: ${unplaced.map((p) => p.id).join(", ")}.`, "");

  push("## Connections", "");
  const edgeFactsByConnection = new Map<string, string[]>();
  for (const f of o.edges) if (f.research?.connection) edgeFactsByConnection.set(f.research.connection, [...(edgeFactsByConnection.get(f.research.connection) ?? []), `${f.label} (\`${f.ref.edgeId}\`, ${lower(f.activation)})`]);
  const historicalByConnection = new Map(o.historical.filter((h) => h.connectionId).map((h) => [h.connectionId!, h]));
  push(...table(["Research", "Between", "Research status", "UW Go"], r.connections.map((c) => {
    const decision = edgeFactsByConnection.get(c.id)?.join("; ")
      ?? (historicalByConnection.has(c.id) ? `historical: never routed (${historicalByConnection.get(c.id)!.removed})` : "not in the survey, not routed");
    return [c.id, `${c.from}–${c.to} (${c.connectionType})`, c.status, decision];
  })));
  push("");

  push("## Links that no longer exist", "");
  for (const h of o.historical) push(`- ${h.kind.toLowerCase()} ${h.between.join("–")}${h.connectionId ? ` (${h.connectionId})` : ""}: ${h.removed}. ${h.basis}`);
  push("");

  push("## Opening hours", "");
  for (const b of o.buildings.filter((x) => x.availability)) {
    const a = b.availability!;
    const v = a.value;
    const when = v.kind === "SCHEDULE"
      ? v.windows.map((w) => `days ${w.days.join(",")} ${Math.floor(w.open / 60)}:${String(w.open % 60).padStart(2, "0")}–${Math.floor(w.close / 60)}:${String(w.close % 60).padStart(2, "0")}`).join("; ") + (v.unknownDays?.length ? `; unknown on days ${v.unknownDays.join(",")}` : "")
      : lower(v.kind);
    push(`- **${b.code}**: ${when} (${a.ruleId ?? ""}, ${lower(a.evidence)}). ${a.basis}`);
  }
  push("", "Every other building's hours are unknown. A route only passes through a building with unknown hours between 07:00 and 22:00; this is UW Go's policy, not a fact about the building, and it never stops a trip that starts or ends there.", "");

  push("## Conflicts", "");
  for (const c of o.conflicts) {
    push(`### ${c.subject} (\`${c.id}\`)`, "");
    for (const p of c.positions) push(`- ${p.says}${p.sourceIds.length ? ` [${p.sourceIds.join(", ")}]` : " [survey]"}`);
    push("", `Treatment: ${c.treatment}`, "");
  }

  push("## Field verification backlog", "", "Things to walk out and check, as reviewers wrote them down. Priority 1 blocks a production decision; 2 would improve routing; 3 completes the inventory. The list to walk, ranked from what UW Go actually routes and with exactly what to check at each place, is `docs/campus-field-verification.md`; record findings as observation files (see `src/data/campus/field/README.md`).", "");
  push(`Promoted field observations: ${k.promotions.length}.${k.promotions.length ? ` ${k.promotions.map((p) => `${p.id} (${p.observedOn}, by ${p.verifiedBy.join(", ")})`).join("; ")}.` : ""}`, "");
  const placementChecks: FieldCheck[] = placements
    .filter((f) => f.research?.portals?.length)
    .map((f) => ({
      id: `FC_PLACEMENT_${f.ref.edgeId}`,
      priority: f.evidence === "CORROBORATED" ? 2 : 3,
      where: f.label,
      question: `Is the surveyed door at \`${f.ref.edgeId}\` the ${(f.research!.portals!).map((id) => `${id} "${k.portals.get(id)?.description}"`).join(" / ")}? Record its coordinates, which way it may be used, and its hours.`,
      why: `Placed as ${lower(f.evidence)} by UW Go, not observed.`,
      edgeIds: [f.ref.edgeId],
    }));
  for (const p of [1, 2, 3] as const) {
    push(`### Priority ${p}`, "");
    for (const f of [...o.fieldChecks, ...placementChecks].filter((x) => x.priority === p)) {
      const refs = [...(f.research?.portals ?? []), ...(f.research?.connections ?? []), ...(f.research?.rules ?? []), ...(f.edgeIds ?? []).map((id) => `\`${id}\``)];
      push(`- [ ] **${f.where}**: ${f.question} _${f.why}_${refs.length ? ` (${refs.join(", ")})` : ""}`);
    }
    push("");
  }

  push("## Research leads not routed", "", "Route candidates are kept for measurement. None is routed as a sequence; where one names a door or link UW Go does use, that part is routed on its own evidence.", "");
  push(...table(["Id", "Journey", "Sequence", "Evidence", "Limitation"], r.routeCandidates.map((c) => [c.id, c.originDestination, c.sequence.join(" → "), lower(c.evidence), c.limitation])));
  push("");

  push("## Coverage", "");
  const surveyedBuildings = new Set([...surveyed.values()].flatMap((s) => [...s.between]).filter((b) => b !== "OUT"));
  const onNetwork = r.buildings.filter((b) => surveyedBuildings.has(b.id)).map((b) => b.id);
  const offNetwork = r.buildings.filter((b) => !surveyedBuildings.has(b.id)).map((b) => b.id);
  push(
    `${onNetwork.length} of ${r.buildings.length} research buildings are on the surveyed network: ${onNetwork.join(", ")}.`,
    "",
    `Not on it, so routed by Google to their map point as before: ${offNetwork.join(", ")}.`,
    "",
    `Surveyed segments: ${surveyed.size}. Segments with a reviewed fact: ${o.edges.length}.`,
    "",
  );

  push("## Sources", "");
  push(...table(["Id", "Title", "Publisher", "Type", "Published"], r.sources.map((s) => [s.id, `[${s.title}](${s.url})`, s.publisher, s.sourceType, s.publishedDate ?? "undated"])));
  push("");
  return out.join("\n");
}
