/**
 * docs/campus-field-verification.md: the field checks in the order to walk them. Each says where to stand
 * and how far that position can be trusted, why it ranks where it does, what UW Go believes now, and
 * exactly what to check. Rendered from the targets and the generated ranking by `npm run campus:field`; a
 * test keeps it current.
 */
import type { FieldTargetKind } from "@/data/campus";
import type { FieldTarget } from "./fieldTargets";
import { OUTDOOR_PENALTY } from "./indoorGraph";
import {
  DEMAND_ROLES,
  EVIDENCE_UNCERTAINTY,
  GAINED_SECONDS,
  LOST_SECONDS,
  RANKING,
  STAND_IN_WALK,
  TIERS,
  priorityReasons,
  type FieldPriorities,
  type TargetPriority,
  type Tier,
} from "./fieldPriority";

const TIER_TITLE: Record<Tier, string> = { P0: "P0 — verify immediately", P1: "P1 — high value", P2: "P2 — useful", P3: "P3 — low urgency" };

const TIER_MEANING: Record<Tier, string> = {
  P0: "Nobody has checked it on the ground, and a decision UW Go makes today stands or falls with it: a rule it corrects walks with, the only allowed way in for a corrected walk, a door it sends students to that a reviewer has flagged or sources dispute, or the highest scores.",
  P1: "Nobody has checked it on the ground, and UW Go sends students through it instead of Google's walk, much routing relies on it, or confirming it would open a step-free way or a shortcut; or it scores high on all of that together.",
  P2: "Some routing relies on it, sources disagree about it, or a reviewer asked for it.",
  P3: "Little or nothing relies on it yet. Worth doing when passing.",
};

const KIND_WORD: Record<FieldTargetKind, string> = {
  DOOR: "door", LINK: "link", VERTICAL: "change of floor", PORTAL: "research door, unplaced", RULE: "rule", HOURS: "hours", CHECK: "open question", LEAD: "research lead",
};

const KIND_HEADING: Record<FieldTargetKind, string> = {
  DOOR: "Doors to outside", LINK: "Links between buildings", VERTICAL: "Changes of floor", PORTAL: "Research doors not yet placed", RULE: "Rules about a way in", HOURS: "Opening hours", CHECK: "Open questions", LEAD: "Research leads",
};

const lower = (s: string) => s.toLowerCase().replace(/_/g, " ");
const pct = (x: number) => `${(x * 100).toFixed(x < 0.01 ? 2 : 1)}%`;

function where(t: FieldTarget): string {
  if (!t.location) return "No single place.";
  const { lat, lng } = t.location;
  const kind = t.location.precision === "SURVEYED" ? "surveyed position" : "approximate: the building's map point";
  return `${lat.toFixed(6)}, ${lng.toFixed(6)} (${kind}; [map](https://www.google.com/maps/search/?api=1&query=${lat.toFixed(6)},${lng.toFixed(6)})). ${t.location.note}`;
}

function detailed(n: number, t: FieldTarget, p: TargetPriority): string[] {
  const out = [
    `### ${n}. ${t.name}`,
    "",
    `\`${t.id}\` · ${KIND_WORD[t.kind]}${t.building ? ` · ${t.building}` : ""} · score ${p.score}${p.critical ? " · critical" : ""} · evidence ${lower(t.shown.evidence)}`,
    "",
    `**Where**: ${where(t)}`,
    "",
    "**Why it ranks here**",
    "",
    ...priorityReasons(t, p).map((r) => `- ${r}`),
    ...t.why.map((w) => `- ${w}`),
    "",
    "**What UW Go believes now**",
    "",
    ...t.current.map((c) => `- ${c}`),
    "",
    "**Check**",
    "",
    ...t.toCheck.map((c) => `- [ ] ${c}`),
    "",
  ];
  if (t.research.length) out.push(`**Research**: ${t.research.map((r) => `${r.id} (${lower(r.evidence)}): ${r.text}`).join(" ")}`, "");
  if (t.sourceIds.length) out.push(`**Sources**: ${t.sourceIds.join(", ")}`, "");
  return out;
}

function compact(t: FieldTarget, p: TargetPriority): string[] {
  return [
    `- **${t.name}** (\`${t.id}\`, ${KIND_WORD[t.kind]}, score ${p.score}). ${priorityReasons(t, p).slice(0, 2).join(" ")}`,
    `  Where: ${where(t)}`,
    `  Now: ${t.current.join(" ")}`,
    `  Check: ${t.toCheck.map((c, i) => `(${i + 1}) ${c}`).join(" ")}`,
  ];
}

export function renderFieldVerificationDoc(targets: readonly FieldTarget[], priorities: FieldPriorities): string {
  const ranked = targets
    .map((t) => ({ t, p: priorities.targets[t.id] }))
    .filter((x): x is { t: FieldTarget; p: TargetPriority } => Boolean(x.p))
    .sort((a, b) => TIERS.indexOf(a.p.tier) - TIERS.indexOf(b.p.tier) || b.p.score - a.p.score || (a.t.id < b.t.id ? -1 : 1));
  const inTier = (tier: Tier) => ranked.filter((x) => x.p.tier === tier);
  const g = priorities.generatedFrom;
  const kinds = Object.keys(KIND_HEADING) as FieldTargetKind[];
  const out: string[] = [];
  const push = (...lines: string[]) => out.push(...lines);

  push(
    "# Campus field verification",
    "",
    `Generated by \`npm run campus:field\` from the campus network (WATIsGrass ${g.networkCommit}), the research and UW Go's reviewed decisions (reviewed ${g.knowledgeReviewedAt}), and ${g.promotions} promoted field observation${g.promotions === 1 ? "" : "s"}. Do not edit by hand; a test fails when this file or the ranking behind it is out of date.`,
    "",
    "What to check on campus, most important first. The ranking comes from what UW Go actually routes: its campus-aware walk decisions, its winter routes and its step-free routes between every pair of places, each trip weighted by how busy its two places are. Each target is scored on how much of that relies on it, what losing or confirming it would change, how busy its building is, and how sure UW Go is of it. How is at the end.",
    "",
    "Record what you find at `/dev/campus-audit` on your phone. It lists these same targets in this order, shows each on a map, and keeps what you record on the phone until you export it. Nothing recorded there changes a route until it is imported, reviewed and promoted (see `src/data/campus/field/README.md`).",
    "",
    "| Tier | Targets | What it means |",
    "|---|---|---|",
    ...TIERS.map((tier) => `| ${tier} | ${inTier(tier).length} | ${TIER_MEANING[tier]} |`),
    "",
    "| Kind | P0 | P1 | P2 | P3 |",
    "|---|---|---|---|---|",
    ...kinds.map((kind) => `| ${KIND_HEADING[kind]} | ${TIERS.map((tier) => ranked.filter((x) => x.t.kind === kind && x.p.tier === tier).length).join(" | ")} |`),
    "",
  );

  let n = 0;
  for (const tier of ["P0", "P1"] as const) {
    push(`## ${TIER_TITLE[tier]}`, "", TIER_MEANING[tier], "");
    for (const { t, p } of inTier(tier)) push(...detailed(++n, t, p));
  }

  push(`## ${TIER_TITLE.P2}`, "", TIER_MEANING.P2, "");
  for (const { t, p } of inTier("P2")) push(...compact(t, p));
  push("");

  push(`## ${TIER_TITLE.P3}`, "", TIER_MEANING.P3, "");
  for (const kind of kinds) {
    const of = inTier("P3").filter((x) => x.t.kind === kind);
    if (!of.length) continue;
    push(`### ${KIND_HEADING[kind]} (${of.length})`, "");
    for (const { t, p } of of) {
      const at = t.location ? ` At ${t.location.lat.toFixed(6)}, ${t.location.lng.toFixed(6)} (${t.location.precision === "SURVEYED" ? "surveyed" : "the building's map point"}).` : "";
      push(`- **${t.name}** (\`${t.id}\`, score ${p.score}).${at} Check: ${t.toCheck.join(" ")}`);
    }
    push("");
  }

  const w = RANKING.weights;
  push(
    "## How the ranking works",
    "",
    "**What is routed.** Three kinds of routing, with every trip weighted by its two places:",
    "",
    `- Campus decisions: the campus-aware walk decision (\`src/engine/campusRoute.ts\`) for every ordered pair of the ${g.places} places (the network's buildings, and residences off it), made against a stand-in for Google's walk: the straight line, ${Math.round((STAND_IN_WALK.detour - 1) * 100)}% longer, at ${STAND_IN_WALK.metresPerSecond} m/s. No routing API is asked. ${g.campusTrips} trips get a decision; what counts is where UW Go sends a student somewhere other than that walk.`,
    `- Winter routes, and step-free winter routes, between every ordered pair of network buildings (${g.networkTrips} trips).`,
    "",
    "All of it on a Tuesday at noon in term, inside every opening window, so the ranking is about the network rather than the clock. The stand-in cannot know Google's real walking times, so campus decisions here show corrections (every walk into PAC) rather than shortcuts, which depend on those times.",
    "",
    "**Demand.** A trip weighs the product of its two places' weights. A network building weighs its size, taken from its surveyed corridor length relative to the median (×0.5 to ×2); a residence off the network weighs ×1. Each then takes every role UW Go's own data gives it. UW Go has no campus-wide timetable of rooms, so these roles are the whole of it:",
    "",
    ...DEMAND_ROLES.map((r) => `- ×${r.factor}: ${r.reason}`),
    "",
    "| Place | Weight | Why |",
    "|---|---|---|",
    ...[...priorities.demand].sort((a, b) => b.weight - a.weight || a.code.localeCompare(b.code)).map((d) => `| ${d.code} | ${d.weight} | ${d.reasons.join("; ")} |`),
    "",
    "**Figures for each target.**",
    "",
    "- Reliance: the trips whose route uses it (for campus decisions, the trips UW Go sends through it instead of Google's walk), and their share of weighted demand.",
    `- Losing it: each such trip decided or routed again with it closed, and how much worse it becomes, averaged over all weighted demand. Campus decisions are measured in seconds. Winter and step-free routes are measured as those routes are chosen: seconds, with each second outside counted ${OUTDOOR_PENALTY} times. A trip left with no allowed way in (campus) or no route (winter, step-free) counts ${LOST_SECONDS}.`,
    `- Confirming it: for a quarantined or restricted link, winter and step-free routes with it usable both ways; for a change of floor, step-free routes with a step-free elevator there. The improvement in the same measure, averaged over all weighted demand; a trip that gains a route counts ${GAINED_SECONDS}.`,
    "- Traffic: the share of weighted demand starting or ending at any building it touches (both of a link's buildings). For a rule about a building's way in or out, the share of weighted demand whose walk UW Go corrects on that rule's word; for a building's hours, the share whose campus decision or winter route passes through the building, each trip counted once.",
    "",
    "**Factors**, each 0 to 1 relative to the target that scores highest on it:",
    "",
    `- routing: the largest of, for each kind of routing (campus ×${RANKING.modeWeights.campus}, winter ×${RANKING.modeWeights.winter}, step-free ×${RANKING.modeWeights.stepFree}), half its reliance and half the cost of losing it; for a rule, its corrected share; for hours, the routing that passes through the building, each trip weighted as the heaviest kind of routing that does, ×${RANKING.hoursRoutingScale}, since unknown hours only change routes before 07:00 and after 22:00;`,
    "- traffic; shortcut: the winter improvement if confirmed; accessibility: the larger of the step-free improvement if confirmed and half the step-free reliance on something whose access nothing routing relies on records.",
    "",
    `**Uncertainty**, 0 to 1, in two parts. For using it: by evidence (${Object.entries(EVIDENCE_UNCERTAINTY).map(([e, u]) => `${lower(e)} ${u}`).join(", ")}), except ${RANKING.surveyedStairwellUncertainty} for a surveyed stairwell, which rarely turns out not to be there; plus ${RANKING.conflictUncertainty} for each disagreement between sources and ${RANKING.urgentCheckUncertainty} for a check a reviewer marked urgent. For its access: 1 for a change of floor nobody has confirmed step-free, ${RANKING.unknownAccessUncertainty} for a door or link whose access nothing routing relies on records, otherwise by evidence.`,
    "",
    `**Score** = 100 × (${w.routing} × routing × uncertainty for using it + ${w.traffic} × traffic × uncertainty for using it + ${w.shortcut} × shortcut + ${w.accessibility} × accessibility × uncertainty about access).`,
    "",
    "**Tiers.**",
    "",
    `- P0: not field-verified, and either critical (a rule UW Go corrects walks with, or without it a corrected walk has no allowed way in), or UW Go sends at least ${pct(RANKING.p0CampusShare)} of weighted demand through it instead of Google's walk while a reviewer has flagged it, sources disagree about it or its evidence is no better than surveyed, or a score of ${RANKING.p0Score} or more.`,
    `- P1: a score of ${RANKING.p1Score} or more; or not field-verified, and UW Go sends any trip through it instead of Google's walk, or routing, accessibility or shortcut, each with its uncertainty, reaches ${RANKING.p1Factor}.`,
    `- P2: a score of ${RANKING.p2Score} or more, campus and winter reliance on at least ${pct(RANKING.p2Share)} of weighted demand, a disagreement between sources, or a reviewer's check of priority 1 or 2.`,
    "- P3: everything else.",
    "",
    "**What it cannot see.** Google's real walking times, and so which shortcuts UW Go would take against them; trips from anywhere other than the network's buildings and residences; when in the day trips are made; and any door or link the survey never drew.",
    "",
  );
  return out.join("\n");
}
